### ISSUE TITLE
Enlarge regex text box

### ISSUE THREAD

**Issue by Flare576** [nathanielknight/wordle-aug#4]
Consider increasing the width of the regex box to around the size of the "Exclude words containing" keyboard.

**Comment by Flare576** [comment]
Just saw this is subset of the stuff mentioned in #3... I don't know the etiquette here lol

**Comment by nathanielknight** [comment]
There are no rules!

**Comment by nathanielknight** [comment]
5ee5ab82807ce72944d682c62b3f8038385f4b8e (now live) might have what you're after?

**Comment by Flare576** [comment]
Like a boss
